### ISSUE TITLE
No target for debian/jessie

### ISSUE THREAD

**Issue by rwillmer** [ckan/ckan-packaging#8]
I need a version of this which generates a package for debian/jessie.

I'll give you a PR for it.

**Comment by rwillmer** [comment]
It looks as though I should be able to use the trusty build on jessie; but that isn't building from scratch.

**Comment by rwillmer** [comment]
Fixed the building problem, see #9. But this is what I get when I apply trusty build to jessie

```
Setting up python-ckan (2.6.0-trustytest5) ...
D000001: deferred_configure updating conffiles
D000002: fork/exec /var/lib/dpkg/info/python-ckan.postinst ( configure  )
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 7, in <module>
    from paste.script.command import run
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 3, in <module>
    import pkg_resources
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 35, in <module>
    import plistlib
  File "/usr/lib/python2.7/plistlib.py", line 62, in <module>
    import datetime
ImportError: No module named date time
```

**Comment by rwillmer** [comment]
This problem is caused by the fact that the virtualenv installed into /usr/lib/ckan/default is old, and does not have datetime built-in. Investigating what causes this.
```
root@868557ced7ed:/# /usr/lib/ckan/default/bin/python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
root@868557ced7ed:/# python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by rwillmer** [comment]
This python 2.7.6 is what the standard Vagrant trusty has installed.
```
$ vagrant ssh trusty
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-107-generic x86_64)
$ python -V
Python 2.7.6
```

**Comment by rwillmer** [comment]
Trusty is, and always, will be constrained to python 2.7.6.

Rather than fighting with this, I will build a debian/jessie package, as originally planned.

**Comment by rwillmer** [comment]
I believe I have a working jessie package now, will submit PR tomorrow once I've verified it.
